//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stockfaesdbEntities : DbContext
    {
        public stockfaesdbEntities()
            : base("name=stockfaesdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<FileDetail> FileDetails { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TB_articles> TB_articles { get; set; }
        public virtual DbSet<TB_bonEntre> TB_bonEntre { get; set; }
        public virtual DbSet<TB_bonRequisition> TB_bonRequisition { get; set; }
        public virtual DbSet<TB_bonSortie_stock> TB_bonSortie_stock { get; set; }
        public virtual DbSet<TB_categorie> TB_categorie { get; set; }
        public virtual DbSet<TB_detail_requisition> TB_detail_requisition { get; set; }
        public virtual DbSet<TB_detail_sortie> TB_detail_sortie { get; set; }
        public virtual DbSet<TB_direction> TB_direction { get; set; }
        public virtual DbSet<TB_employe> TB_employe { get; set; }
        public virtual DbSet<TB_livraison> TB_livraison { get; set; }
        public virtual DbSet<TB_lot_entrestock> TB_lot_entrestock { get; set; }
        public virtual DbSet<TB_mouvement_stock> TB_mouvement_stock { get; set; }
        public virtual DbSet<TB_stock> TB_stock { get; set; }
    }
}
