//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_detail_requisition
    {
        public int Id_details_requisition { get; set; }
        public Nullable<int> Id_bon_requisition { get; set; }
        public Nullable<int> Id_articles { get; set; }
        public Nullable<int> Quantite { get; set; }
        public Nullable<System.DateTime> Date_requisition { get; set; }
    
        public virtual TB_articles TB_articles { get; set; }
        public virtual TB_bonRequisition TB_bonRequisition { get; set; }
    }
}
